// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

const dbUrl = process.env.DIRECT_URL ?? process.env.DATABASE_URL;

if (!dbUrl) {
  throw new Error(
    "Prisma config requires DIRECT_URL or DATABASE_URL. Set one of them before running Prisma commands."
  );
}

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
    seed: "tsx prisma/seed.ts",
  },
  datasource: {
    url: dbUrl,
  },
});