// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

// DIRECT_URL is only required at runtime (migrations, db push, etc.).
// During the build phase, `prisma generate` only reads the schema file to
// produce TypeScript types and does not open a database connection, so a
// placeholder URL is safe to use when the variable is not set.
const datasourceUrl =
  process.env.DIRECT_URL ?? "postgresql://placeholder:placeholder@localhost:5432/placeholder";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
    seed: "tsx prisma/seed.ts",
  },
  datasource: {
    url: datasourceUrl,
  },
});
